version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: myDBName
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/src
    environment:
      CLIENT_ORIGIN: http://localhost:8080
      PORT: 3000
      DB_HOST: mongo
      DB_NAME: myDBName
      DB_PORT: 27017
      NODE_ENV: development
      IS_LOCAL_MONGO: 'true'
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongodb: